- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Install PyMySQL for Python3 
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3.9

- name: Check if MySQL root password works
  ansible.builtin.shell: |
    mysql -h {{MYSQL_HOST}} -u root -p{{ MYSQL_ROOT_PASSWORD }} -e "SELECT 1;" >/dev/null 2>&1
  register: root_pass_check
  ignore_errors: yes
  changed_when: false

- name: Debug root password check
  ansible.builtin.debug:
    msg: "MySQL root password check RC = {{ root_pass_check.rc }}"

- name: Setup MySQL root password if not set
  ansible.builtin.shell: |
    mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"
  when: root_pass_check.rc != 0
  changed_when: true

# - name: Set MySQL root password if not set
#   community.mysql.mysql_user:
#     login_user: "{{ MYSQL_ROOT_USER }}"
#     login_password: ''
#     user: "{{ MYSQL_ROOT_USER }}"
#     host_all: yes
#     password: "{{ MYSQL_ROOT_PASSWORD }}"
#     state: present
#   when: root_pass_check.rc != 0