- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
  - maven
  - mysql

- name: Install PyMySQL and cryptography for Python3
  ansible.builtin.pip:
    name: "{{item}}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: "mv target/{{ component }}-1.0.jar {{ component }}.jar" 
  args:
    chdir: /app